### ISSUE TITLE
PDF as release

### ISSUE THREAD

**Issue by YodaEmbedding** [HugoForrat/LaTeX-Vim-User-Manual#1]
It's better to keep non-source/build files outside source control. I recommend putting your PDF in [releases](https://github.com/HugoForrat/LaTeX-Vim-User-Manual/releases) and linking that in the README for discoverability.

**Comment by HugoForrat** [comment]
You're absolutely right. This is my first GitHub repo and I forgot about best practices.

This has been corrected, thanks a lot.
